Update build-docker-compose.yml

diff --git a/.github/workflows/build-docker-compose.yml b/.github/workflows/build-docker-compose.yml
--- a/.github/workflows/build-docker-compose.yml
+++ b/.github/workflows/build-docker-compose.yml
@@ -10,7 +10,7 @@ permissions:
   packages: write    
 
 jobs:
-  download_betterfront_docker_image:
+  create_docker_compose:
     runs-on: ubuntu-latest
 
     steps:
@@ -31,5 +31,35 @@ jobs:
           docker images --format '{{.Repository}}:{{.Tag}}' | grep -q '^betterfront:latest$' \
           && echo "Image found ✅" \
           || (echo "Image NOT found ❌" && exit 1)
+          
+      - name: Checkout BetterJava repository
+        uses: actions/checkout@v4
+
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '21'
+          
+      - name: Make gradlew executable
+        run: chmod +x ./gradlew   
+
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+
+      - name: Build with Gradle
+        run: ./gradlew clean build
+
+      - name: Build Docker Compose images
+        run: docker-compose -f ./docker-compose.yaml build
+
+      - name: Verify BetterFront Docker image
+        run: |
+          docker images --format '{{.Repository}}:{{.Tag}}' | grep -q '^betterfront:latest$' \
+          && echo "BetterFront image built ✅" \
+          || (echo "BetterFront image not found ❌" && exit 1)
+   
+   
+    
   
        
